from pywk99.significance.coherence import coherence_squared_significance
from pywk99.significance.bootstrap_difference import bootstrap_difference_test
from pywk99.significance.permutation_difference import permutation_difference_test
from pywk99.significance.statistics import log_distance_statistic
from pywk99.significance.statistics import coh2_distance_statistic