name: Test Python Package using Conda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: environment.yml
        generate-run-shell: true   
    - name: Test with pytest
      run: pytest
      shell: micromamba-shell {0}
